name = "GraphClustering"
uuid = "8ff72e77-ac1c-440e-8064-6af5ea7625d8"
authors = ["GiggleLiu"]
version = "1.0.0-DEV"

[deps]
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LuxorGraphPlot = "1f49bdf2-22a7-4bc4-978b-948dc219fbbc"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
