name = "HiddenMarkovModel"
uuid = "9fa66fbd-4335-469e-840d-99b9fe4b4253"
authors = ["GiggleLiu <cacate0129@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OMEinsum = "ebe7aa44-baf0-506c-a96f-8464559b3922"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
LinearAlgebra = "1.11.0"
OMEinsum = "0.8.5"
Random = "1.11.0"
StatsBase = "0.34.4"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
