name = "SpinDynamics"
uuid = "14ef36e5-90ab-499e-a97f-72c4e36abdb5"
authors = ["GiggleLiu <cacate0129@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
CairoMakie = "0.13.2"
Graphs = "1.12.0"
LinearAlgebra = "1.11.0"
StaticArrays = "1.9.13"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
